### ISSUE TITLE
Apply back pressure if APM server is not available or overloaded

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-agent-java#10]
...by not sampling transactions when the queue is almost full and not recording transactions and events at all if the queue is completely full.

See also https://mechanical-sympathy.blogspot.com/2012/05/apply-back-pressure-when-overloaded.html

**Comment by alvarolobato** [comment]
Related to https://github.com/elastic/apm-agent-java/issues/64 and not clear how we are going to implement it yet.

**Comment by mariskamartin** [comment]
OK

Dne 28. 5. 2018 14:51 napsal uživatel "Alvaro Lobato" <
notifications@github.com>:

Related to #64 <https://github.com/elastic/apm-agent-java/issues/64> and
not clear how we are going to implement it yet.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/elastic/apm-agent-java/issues/10#issuecomment-392518974>,
or mute the thread

**Comment by felixbarny** [comment]
duplicate of #64
