### ISSUE TITLE
the http status code on kibana is 500， but the actual http status code is 200

### ISSUE THREAD

**Issue by CoderLan0668** [elastic/apm-agent-java#1036]
## Describe the bug
in the Spring web project，internal code invocation throws an exception，but we use @ControllerAdvise and @ExceptionHandler to handle it， and it sned 200（http status code） and error message that we expected。

as we take the configuration that ignore this exception，and it‘s not collected as an ERROR， it is good。

but the problem is： the trace is reported as http 5xx on the kibana。

## Steps to reproduce
it‘s well described by the above text

## Expected behavior
expecte the trace is shown with the actual http status code：200

**Comment by SylvainJuge** [comment]
Hi, @CoderLan0668,

If I understand correctly, your application throws an exception that is caught an handled with a [Spring exception handler](https://docs.spring.io/spring/docs/3.2.x/spring-framework-reference/html/mvc.html#mvc-ann-exceptionhandler), and the answer is transformed to return a 200 HTTP status code.

By default, our agent instruments Spring `DispatcherServlet` with `ExceptionHandlerInstrumentation` in order to capture this exception and thus mark the transaction in error. Thus without any extra configuration it means that those transactions will be reported as ERROR with a 500 status code.

In your case, to get back to the expected transaction state, you should simply disable `exception-handler` instrumentation with `disable_instrumentations=xception-handler`.

Also, in the future, it's best to start discussing this kind of issues [in our forum] first (https://discuss.elastic.co/) as we try to keep github issues for actionable items and linked to code changes in the agent.

**Comment by CoderLan0668** [comment]
not only ExceptionHandlerInstrumentation。

in the case, Spring DispatcherServlet will put the exception into the http request object, @see DispatcherServlet#processHandlerException

the exception was put into the attribute in the http request object, with key "org.springframework.web.servlet.DispatcherServlet.EXCEPTION"

and the **ServletApiAdvice#onExitServletService** will try to find an exception through the http request object, if an exception is  found,  the status will set to 500( **ServletTransactionHelper#doOnAfter**)

i think hte behavior that the agent find any exception through the http request object and mark the http request has error is ok， but the exception found should be check that if it can be ignored （what about the core configuration -- ignore_exceptions?）

**Comment by felixbarny** [comment]
I think adding `ignore_exceptions` makes sense. But ideally, we should automatically detect that the status should not be set to 500.

The problematic lines are these:

https://github.com/elastic/apm-agent-java/blob/9528d35842985671e90f20e9699ad27cc21a8f30/apm-agent-plugins/apm-servlet-plugin/src/main/java/co/elastic/apm/agent/servlet/ServletTransactionHelper.java#L177-L180

We do that as usually, servlet containers set the status to 500 if there's an exception. In this case, however, the exception does not come from the `javax.servlet.error.exception` attribute but `org.springframework.web.servlet.DispatcherServlet.EXCEPTION`. So, in this case, we probably shouldn't run the same logic as the exception has already been handled by Spring and the servlet container won't set the status code.
