### ISSUE TITLE
Need DB spans duration threshold, similar to trace_methods_duration_threshold

### ISSUE THREAD

**Issue by sudhireer868** [elastic/apm-agent-java#1094]
## Is your feature request related to a problem?
Need DB spans duration threshold, similar to trace_methods_duration_threshold. If the DB spans does not have threshold even the minor spans (1 or 2 micro seconds spans)are reported in APM timeline and messing up the timeline for large transactions.

## Describe the solution you'd like
Please provide configuration parameter for DB spans so that spans above threshold only would be captured and showed in the timeline.

**Comment by SylvainJuge** [comment]
Hi @sudhireer868,

What kind of short-lived database interactions do you need to ignore ?
What is the usual duration of your transactions ?
Can you provide a screenshot of what it looks like on transaction timeline ?

Performance wise, having a large count of small interactions with a DB can often be a major source of application slowness due to network latency.

Doing this only for DB spans is very narrow and specific to your use-case, if we add this feature, we need to think about doing it for all span types.

Please note that we usually recommend to ask first in the forum for this kind of requests/questions, we try to keep the github issues when actual changes are required in the agent (and those are property defined). As a result, we are quite likely to close this issue, but we'd be happy to discuss this further on https://discuss.elastic.co/.

**Comment by sudhireer868** [comment]
@SylvainJuge It is legacy application which we have to live with. Attached 2 sample screenshots for reference from our application. We have lot of such spans filling up the complete timeline, so asked for this feature to remove such small spans and show up only the time taking spans.

<img width="682" alt="DB1" src="https://user-images.githubusercontent.com/61221358/78024279-b7c91d00-7375-11ea-9c10-38fa10aabbec.PNG">

<img width="694" alt="DB2" src="https://user-images.githubusercontent.com/61221358/78024308-c31c4880-7375-11ea-9a81-b44f32ae2488.PNG">

**Comment by SylvainJuge** [comment]
I feel that it's something that would be better handled at UI level in Kibana, there is already an issue to allow filtering by span types, thus adding "span duration" to the existing issue: https://github.com/elastic/kibana/issues/40304 seems relevant.

Doing this at agent level would likely have unexpected side effects like partially monitored transactions and inconsistent timings.

**Comment by sudhireer868** [comment]
@SylvainJuge Your proposal to add "Span duration" to Kibana UI is also fine so that we can filter out the unwanted spans.

**Comment by duclm2609** [comment]
I also need DB span threshold for the same reason. I only want to collect DB span that is above a desired threshold.
