### ISSUE TITLE
APM Agent on K8s take wrong service memory

### ISSUE THREAD

**Issue by hramos8** [elastic/apm-agent-java#1197]
**Describe the bug**
When using APM agent on Kubernetes cluster, the memory reported in **system.process.memory.size** is incorrect.

To identify this situation whe have the suport of @tanquetav

**To Reproduce**
1. In kibana, search your service metrics:
`service.name : your-service-name and processor.event : metric`
this value isn't the service memory value, this value is too hight. Maybe this is the memory of all services on host?

**Expected behavior**
The correct value of the service.

**Comment by eyalkoren** [comment]
Thanks for reporting this.
Please provide some more info:
- versions of the Java agent, APM server, Elasticsearch and Kibana are you using
- some details about your k8s deployment - version, OS, containers (platform/version/base-image)
- please set [`debug_level`](https://www.elastic.co/guide/en/apm/agent/java/current/config-logging.html#config-log-level) to `TRACE`, let it run for a few minutes and upload the log
- does you cluster contain more than one pod running the same service? 
- please describe or add a screenshot of your `JVMs` tab, and a specific JVM's metrics dashboard

**Comment by felixbarny** [comment]
We're getting the memory metrics from `/proc/meminfo`. See also

https://github.com/elastic/apm-agent-java/blob/d10d713e857bd9fe9ce72414f77b7578718a2bbc/apm-agent-core/src/main/java/co/elastic/apm/agent/metrics/builtin/SystemMetrics.java#L117-L164

This issue seems related: https://github.com/google/cadvisor/issues/2042

**Comment by tanquetav** [comment]
Yes, the problem is related to reads memory from /proc/meminfo. Unfortunately this information is not cgroups compliant, and gives the information from host environment. The cgroup information is available on /sys/fs/cgroup/
```
[george@casa02 apm-agent-dotnet]$ docker run -it --rm -m 500m ubuntu:latest /bin/bash
root@0b787d6c9417:/# cat /proc/meminfo |grep Mem
MemTotal:       16269404 kB
MemFree:          282024 kB
MemAvailable:    4454260 kB
root@0b787d6c9417:/# cat /sys/fs/cgroup/memory/memory.limit_in_bytes
524288000
```
The -m flag tells docker to limit the container to 500Mb, but /proc/meminfo shows 16G. The correct information is available in cgroup environment.

I hope it can help to fix this issue

**Comment by eyalkoren** [comment]
@elastic/apm-agent-devs FYI, relevant to any agent that is relying on `/proc/meminfo` to get system memory. See also related PR.
