### ISSUE TITLE
Derive trace ID from a trace ID coming from LB

### ISSUE THREAD

**Issue by nikita2206** [elastic/apm-agent-java#1201]
## Is your feature request related to a problem?
Our application gets HTTP requests from a chain of AWS ELB -> haproxy load balancers. ELB adds its `X-Amzn-Trace-Id` header to the requests.

## Describe the solution you'd like
Ideally I’d like to be able to take an upstream trace ID and just use it as an ID of the APM trace as well, this will let me see the entire set of log events for a single request combined. Currently I see the option where in haproxy I could rewrite `X-Amzn-Trace-Id` to `Elastic-APM-Trace-Id` but this sounds a bit flakey (what if a request never makes it to the app or if we migrate off haproxy). As Trace parent is still not accepted, it would be nice to be able to make different LBs and Elastic APM work together. If we could define programmatically in the app, the trace ID derivation function, that would be perfect; but I’m not sure if it’s possible for java code to have some sort of inter communication with java agent.

**Comment by felixbarny** [comment]
The problem is not just the naming of the header. The values are just incompatible with one another. We've started supporting the official w3c `traceparent` header specification. I'm not sure when and if AWS ELB is going to support it but if they do, what you described would work.

What you could do in the meantime is to add the amazon trace id as a label to the transactions created by Elastic APM: https://www.elastic.co/guide/en/apm/agent/java/current/public-api.html#api-transaction-add-tag
