### ISSUE TITLE
Load agent from dedicated agent class loader

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-agent-java#1338]
Stop adding all the agent classes into the bootstrap class loader

- Hides the agent from the regular classpath
- Reduces risk of interfering with classpath scanners

Depends on elastic/apm-agent-java#1337 
Prerequisite for elastic/apm-agent-java#1339

**Comment by eyalkoren** [comment]
When implementing this, consider using the agent class loader for a dedicated log4j context - in `LoggingConfiguration#init` we may want to switch to using `org.apache.logging.log4j.core.config.Configurator#initialize(ClassLoader, Configuration)` instead of the current `org.apache.logging.log4j.core.config.Configurator#initialize(Configuration)` and use that to further separate agent loggers from others.
