### ISSUE TITLE
Does ES-APM support jetcd

### ISSUE THREAD

**Issue by starry-eyed-art** [elastic/apm-agent-java#1357]
Whether ESAPM support jetcd (etcd java client), if you do not support it, if someone is already developing this function?

**Comment by SylvainJuge** [comment]
Hi @starry-eyed-art ,

As stated in [our project readme](https://github.com/elastic/apm-agent-java), we prefer to use github issues for actionable tasks that require changes in the agent. Questions are better served in [our forum > observability > apm](https://discuss.elastic.co/c/observability/apm/), but I agree that the later could be a bit intimidating at first sight :-).

In order to prioritize framework support, it's a never ending task, thus we have [a survey](https://github.com/elastic/apm-agent-java#apm-agent-java) to help us prioritize support. Please fill it so we make sure that jetcd is added to the list.

We currently do not support [jetcd](https://github.com/etcd-io/jetcd), and it's not in our short-term roadmap, thus there are two options:
- implement tracing using agent [public-api](https://www.elastic.co/guide/en/apm/agent/java/current/public-api.html), that requires minimal changes to your application
- contribute to the agent and implement a plugin to add support (see [contributing guide](https://github.com/elastic/apm-agent-java/blob/master/CONTRIBUTING.md)), which might require a more significant effort

As a result, we will close this issue (keeping opened issues for a long time only produces noise), and re-open one when it's  added to our roadmap.
