### ISSUE TITLE
Flaky tests due to connection reset when downloading dependencies

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-agent-java#1375]
## Test method

Happens before tests, in the build phase

## Test logs

```
[2020-09-01T07:08:56.951Z] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M1:enforce (enforce-java) on project apm-agent-parent: Execution enforce-java of goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M1:enforce failed: Plugin org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M1 or one of its dependencies could not be resolved: The following artifacts could not be resolved: org.apache.maven:maven-settings:jar:3.0, org.apache.maven:maven-repository-metadata:jar:3.0, org.apache.maven:maven-model-builder:jar:3.0: Could not transfer artifact org.apache.maven:maven-settings:jar:3.0 from/to central (https://repo.maven.apache.org/maven2): Transfer failed for https://repo.maven.apache.org/maven2/org/apache/maven/maven-settings/3.0/maven-settings-3.0.jar: Connection reset -> [Help 1]
```

## Additional context

Lately, we see a lot of test failures because of `Connection reset` errors.

@elastic/observablt-robots do you know if there are network issues?

Also, why does maven even need to resolve the dependencies? Shouldn't they be cached in the image via packer cache?

**Comment by SylvainJuge** [comment]
There is currently some work being done by the CI team on this, not sure about the current progress and priority though.

**Comment by cachedout** [comment]
We may be able to add this to the [image cache](https://github.com/elastic/apm-agent-java/blob/master/.ci/packer_cache.sh) if it's not there already. I will investigate this.

**Comment by v1v** [comment]
I'm working on something else that seems similar to this issue, and this is my finding:
- Caching is not happening since the .m2 folder is set to another location:
  - https://github.com/elastic/apm-agent-java/blob/master/Jenkinsfile#L17

That particular configuration was there since the very beginning:
- https://github.com/elastic/apm-agent-java/commit/5fccf62177f015f9d7c40fdd98805013a7cd3dd3

https://github.com/elastic/apm-agent-java/pull/1376 might fix this issue, at least the one related to the cached artifacts

**Comment by v1v** [comment]
And guess what! I faced this particular issue in my above-mentioned fix:

For what I read the `-Dhttps.protocols=TLSv1.2` flag seems to be the workaround:

- [build](https://apm-ci.elastic.co/job/apm-agent-java/job/apm-agent-java-mbp/job/PR-1376/2/parameters/) was manually triggered with the above flag as an input parameter

**Comment by cachedout** [comment]
Even with a change to `.m2` won't the fact that we do a `clean install` [here](https://github.com/elastic/apm-agent-java/blob/master/Jenkinsfile#L84) force the download to happen regardless of what's in the cache? Should we remove the `clean` keyword to rely on the cache?

**Comment by v1v** [comment]
the `clean` goal should not affect with the cached dependencies, since it's in charge for the clean up of the generated files within the workspace which are normally hosted in the `target` folder. The only case I imagine it will be required is when the workspace location and the .m2 point to the some location

**Comment by cachedout** [comment]
Yup, I just tested this and was coming back here to say that it doesn't appear to change the caching mechanism so this should be fine.
