### ISSUE TITLE
Turn NoopTransaction and NoopSpan into a public enum 

### ISSUE THREAD

**Issue by manoelstilpen** [elastic/apm-agent-java#1529]
## Is your feature request related to a problem?
I can't access _NoopTransaction_ instance because it defaults to package-private. If it's not a design decision could it be changed?

The same occurs with _NoopSpan_ but **NOT** occurs with _NoopScope_ which is public. Why just one is public?

## Describe the solution you'd like
I'm proposing here changing the access level of those enum to public as _NoopScope_ is.

**Comment by SylvainJuge** [comment]
Currently the Noop implementations are package-private on purpose as it ensures that users of the API do not rely on implementation details of this API (which might change). What would be the use-case that is not possible with the current design ?

**Comment by manoelstilpen** [comment]
@SylvainJuge got it. 

my case is that I have a library and it receives as a parameter a boolean which defines if it should do the tracing or not. To avoid duplicated code and null checks I would like to return Noop instance when this variable is false.

**Comment by eyalkoren** [comment]
@manoelstilpen as @SylvainJuge explained, we prefer the noop implementations are kept out of the API as this leaves us with the ability to change the default implementation without worrying about breaking something to someone. Considering that, would the usage `null` transactions be sufficient for your need after all? If so, please close this issue. Otherwise, you may suggest another alternative.

Good point regarding `NoopScope`, it should be package-private as well. Now we need to worry about it being a potentially breaking change 🙂

**Comment by manoelstilpen** [comment]
Got it thank you @eyalkoren
