### ISSUE TITLE
Support for JAX-RS Client

### ISSUE THREAD

**Issue by tobiasstadler** [elastic/apm-agent-java#1742]
## Is your feature request related to a problem?
We are using JAX-RS client for some of our HTTP request.

## Describe the solution you'd like
JAX-RS client invocations should be instrumented.

**Comment by felixbarny** [comment]
Which JAX-RS client are you using? IIRC, most of them use a supported HTTP client under the hood.

**Comment by tobiasstadler** [comment]
We are using RESTEasy which uses the Apache httpclient under the Good. So yes, tracing already works. But I personally prefer seeing the technologies I am directly using instead of the implementations they are using.

**Comment by eyalkoren** [comment]
@tobiasstadler thanks for your incredible feedback and contributions! 🙏 

In this case, however, we feel it is unlikely we get to that any time soon. Since tracing already works in this case and it is only about naming, we feel it will take a lot of efforts in comparison to the value, assuming that there is no sense on applying this to one client and not the others. 

Besides, we are not even certain whether the proposed naming is superior for all users - while we see why a dev would benefit from knowing the client in use, it is probably less useful for the ops user.

Since there is currently no intention to prioritize this one, would it be OK to close this issue?

**Comment by tobiasstadler** [comment]
I am fine with that
