### ISSUE TITLE
MDC not working in Apache Sling

### ISSUE THREAD

**Issue by bryantcj52** [elastic/apm-agent-java#1786]
The automatic MDC keys doesn't happen early enough for them to show up in the logs when using Apache Sling. Error.id was the only one showing up, although not every time for some reason. I had to create a custom Sling Request Filter and manually add the APM trace/transaction/span IDs to MDC.

I'm not sure if it's possible to add this here if it detects the app is running in sling.

https://gist.github.com/bryantcj52/8e5cce3d1a98d3da89b089bcf230ba61

**Comment by eyalkoren** [comment]
Actually, it may be a matter of timing as well, let me add some debugging capabilities so we can see.

**Comment by bryantcj52** [comment]
@eyalkoren 

https://gist.github.com/bryantcj52/dd805eaf40e5c713675292d4aecb9077

It looks like it can't find any of the MDC classes. Both org.slf4j and org.apache.log4j.MDC should be available.

I'm guessing the java agent is loaded before OSGi sets everything up. Our current bootdelegation: `org.osgi.framework.bootdelegation=co.elastic.apm.*, ${org.apache.sling.launcher.bootdelegation}`

**Comment by eyalkoren** [comment]
> I'm guessing the java agent is loaded before OSGi sets everything up. Our current bootdelegation: org.osgi.framework.bootdelegation=co.elastic.apm.*, ${org.apache.sling.launcher.bootdelegation}

This does not affect the timing of loading, but where our agent classes are loaded from, and it may indeed affect class visibility. This configuration is not required since agent version 1.18.0, so first thing is to remove it (and upgrade if you are using an older agent version 🙂 ).

If this doesn't resolve the issue, it may be a matter of timing, in which case try to set this system property: `-Delastic.apm.delay_agent_premain_ms=5000`

**Comment by bryantcj52** [comment]
Removing the boot delegation and adding the delay (went up to 15 seconds) didn't help.

**Comment by bryantcj52** [comment]
We are using the -javaagent flag for setup, should we switch to the manual Attach API in a bundle activator class? I would assume we would lose any tracking of errors before the bundle starts up?

**Comment by eyalkoren** [comment]
Please try [this analysis snapshot](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-java%2Fapm-agent-java-mbp/detail/PR-1797/1/artifacts) with the following configuration:
```
-Delastic.apm.log_level=debug
-Delastic.apm.log_file=agent/agent.log
-Delastic.apm.log_format_file=json
```

It will format agent log as ECS JSON, including MDC contents. In addition, I added the class loader that we use for MDC lookup to the logs. In the created logs, look for log lines that contain `startTransaction " and paste them here.

In addition, if you can create a dev env, set a breakpoint and debug [`MdcActivationListener#before()`](https://github.com/elastic/apm-agent-java/blob/d7de9d2298c71c9dc5bc3ff55001b4a72f40f7fd/apm-agent-plugins/apm-log-correlation-plugin/src/main/java/co/elastic/apm/agent/mdc/MdcActivationListener.java#L186), you may be able to see what is not working as expected.

**Comment by SylvainJuge** [comment]
Sorry, the related PR was closed due to lack of feedback, and thus the snapshot is not available anymore.

If you are comfortable re-building the agent locally, you can just re-apply the simple change that was in this PR : https://github.com/elastic/apm-agent-java/pull/1797/files and then apply the [configuration recomended by Eyal above](https://github.com/elastic/apm-agent-java/issues/1786#issuecomment-830808726).
