### ISSUE TITLE
Add database/schema name to JDBC spans

### ISSUE THREAD

**Issue by tobiasstadler** [elastic/apm-agent-java#1800]
## Is your feature request related to a problem?
We are using multiple databases during one request. At the moment we cannot really distinguish which db span belongs to which database.

## Describe the solution you'd like
`java.sql.Connection` provides `getCatalog()` and `getSchema()` which can be used to provide additional information for JDBC spans.

## Additional context
We are using PostgreSQL and some of the databases are hosted on the same server, thus we cannot use the `destination.*`

**Comment by tobiasstadler** [comment]
I am unsure how the fields should be named

**Comment by felixbarny** [comment]
We're currently thinking about how to increase the granularity for backends a bit. Your request fits perfectly into that. The goal is to see different clusters of the same database on the service map, such as `postgresql/customers`, `postgresql/orders`. That information would be stored in `destination.service.resource`.

We already have the field `db.instance` but currently, it's not populated. Once we do populate it, we could set `destination.service.resource` to `"${span.subtype}/${db.instance}"`. See also https://github.com/elastic/apm/pull/436

Some questions
* How would you expect your different PostgreSQL database instances to be displayed on the service map.
* How many databases/instances/clusters do you have in your environment?
* What are you using the different DBs for? Could you give us some pseudonymized names? (ex. customers, orders). Totally fine if you don't want to share.
* Where is that db information encoded? In the connection string? What does `getCatalog()` and `getSchema()` return in your case? Are these the expected values?

**Comment by tobiasstadler** [comment]
* I prefer having each database as its own service on the service map (Similar to e.g. a HTTP service). Moreover I would like to see the database name in the "Span details" of the APM app (as our license does not include service maps)
* 6 clusters each with a different number of databases.
* Most of the database have the same shape (let's call them "product") and are used for multiple tenancy of our application. The rest of the databases are either tied to a specific service (e.g. "kms" for our Key Management Service) or shared between all of our applications (e.g. "config" for configuration values).
* either vie the JDBC connection string or via `org.postgresql.ds.common.BaseDataSource#setDatabaseName`. `getCatalog()` returns "product" and `getSchema()` returns "public". Yes, these are the values I expect.

**Comment by wolframhaussig** [comment]
I would like to add my two cents here too as - although we are using Oracle Database instead of PostGreSql - we have a similar requirement:

- We are still on a gold license so I cannot say anything about the service map as I do not know what the service map would look like now
- in our main usecase we currently have 6 database installations wilth multiple users(schemas)
- The Usecase here is a datawarehouse like application where a central server connects to servers in different cities/countries to provide the data.  So the installations might be called Central, Canada, Austria, ... while each user contains data from different sources so the users might be called SAP, AWS, ....
- either vie the JDBC connection string or via java.sql.Connection.setSchema (executes the oracle specific `alter session set current_schema = ?` in the background). getCatalog() returns null, getSchema() returns the schema I expect

**Comment by SylvainJuge** [comment]
Well, your 2 cents might have been well spent @wolframhaussig , as you just made obvious that the meaning of `schema` and `catalog` seems to be really implementation dependent (see related [SO thread](https://stackoverflow.com/questions/7942520/relationship-between-catalog-schema-user-and-database-instance)).

**Comment by SylvainJuge** [comment]
I think that we could have the following behavior to make it work on most databases without per-db specific behavior
- catalog == null && schema == null --> instance = null
- catalog != null && schema != null --> instance = "catalog/schema"
- catalog != null && schema == null --> instance = "catalog"
- catalog == null && schema != null --> instance = "schema"

Does it sounds like a good idea ?

**Comment by SylvainJuge** [comment]
Update: while it initially looked like a good idea, using `Connection#getCatalog` and `Connection#getSchema` is way more complicated than it sounds, thus we will keep `getSchema` out for now at least.

- both `catalog` and `schema` can be changed at runtime during the lifetime of the connection, but not all DB/drivers support that.
- capturing those properties should probably be done on a per-statement basis and at the time when the statement is created as calling `statement.getConnection().getCatalog()` will likely return the *current state* of the connection and not the state of the statement (changing connection catalog won't change the existing statements state).
- support for both of those properties depends on each driver implementation and/or deployment setup, also database connection pools can make those unusable (always throw an exception, or return null).
- `getSchema` is only supported for Java7+ JDBC drivers, thus some DB connection pools written for Java 6 or earlier throw exceptions when trying to call it.
- we can't really query the current state before executing every DB statement, also that would be vendor-specific code.

Alternatively, we could also extend the [JDBC URL parsing logic](https://github.com/elastic/apm-agent-java/blob/master/apm-agent-plugins/apm-jdbc-plugin/src/main/java/co/elastic/apm/agent/jdbc/helper/ConnectionMetaData.java) to guess the database name (or identifier) that could be used for the `instance` field, and then fallback to using `Connection#getCatalog()` only if we can't parse it.

@wolframhaussig in your case, you say that `getCatalog()` always return `null`:
- is that assumption true for the whole lifecycle of the connection object ?
- are you using any db connection pool or are you using the native DB connection ?
- do you set the schema/catalog at runtime using `setCatalog` or `setSchema` ?
- does the values that you get with `getSchema` are somehow reflected in the JDBC URL ? in which case having proper parsing for those would likely work for you ?

**Comment by wolframhaussig** [comment]
@SylvainJuge I just did a test using the connection metadata object using Oracle 12c jdbc library(this is not the newest version though so my answer could be slightly outdated). I am normally using a connection pool(apache dbcp2) but I did the following test on the native connection just to be sure:
- getCatalogs() returns an empty ResultSet (Description: `Get the catalog names available in this database.`)
- getCatalogSeparator() returns an empty string (Description: `What's the separator between catalog and table name?`)
- getCatalogTerm() returns an empty string (Description: `What's the database vendor's preferred term for "catalog"?`)

Therefore, I assume that the catalog will never be set for Oracle databases. 
As described in my first answer we set the schema mostly in the connection(username) but sometimes also using setSchema() which would not reflect in the url. But this is not a blocking from point in my point of view - just a nice to have feature - so processing the JDBC url would be fine by me.

Unfortunately, the JDBC url parsing has a drawback too - at least for Oracle: 
1. Let's look at the following example urls:
- `jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=myhost1)(PORT=1501))(CONNECT_DATA=(SERVICE_NAME=accounting.munich.mycompany.de)))`
- `jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=myhost1)(PORT=1501))(CONNECT_DATA=(SID=accounting)))`
- `jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=myhost2)(PORT=1501))(CONNECT_DATA=(SERVICE_NAME=accounting.berlin.mycompany.de)))`

I guess that you would parse the Servicename/SID from those connections and therefore handle all 3 of them as different databases but in fact, the first two connections point to the same database. In a defined environment this might not be a problem as a single developer/administrator might use either SID or service name all the time but in different teams this might not be true.

2. Another problem is that applications might not have the connection name configured within the jdbc connection string but rather in the Oracle tnsnames.ora:
Let's assume I have a tnsnames.ora with the following content:
```
accounting.munich.mycompany.de =
  (DESCRIPTION =
    (ADDRESS =
      (PROTOCOL = TCP)
      (HOST = myhost1)
      (PORT = 1501)
    )
    (CONNECT_DATA =
      (accounting.munich.mycompany.de)
    )
  ) 
```
Then I could use the following connection string to connect: `jdbc:oracle:thin:@accounting.munich.mycompany.de`. Pretty straight forward to parse, right? The difficulty here is that the name of the connection is a free text that is not necessarily the same as the database name. A realworld example where this would fail in our department:
```
accounting.munich.mycompany.de =
  (DESCRIPTION =
    (ADDRESS =
      (PROTOCOL = TCP)
      (HOST = myhost1-q)
      (PORT = 1501)
    )
    (CONNECT_DATA =
      (accounting-q.munich.mycompany.de)
    )
  ) 
```
Here, the production name in the tnsnames.ora points to the test system as we do weekly copies of the production system to our test system and we do not want to update all synonyms, functions, ... so we only point the tnsnames.ora file to the correct database.

3. Although we do not use the loadbalancing feature I want to add this problem here as another user of Elastic might run into this:
The following tnsnames.ora entry is a valid example of the loadbalancing feature:
```
accounting.mycompany.de= 
(DESCRIPTION_LIST=
 (DESCRIPTION=
  (ADDRESS=...)
  (CONNECT_DATA=(SERVICE_NAME=accounting.munich.mycompany.de)))
 (DESCRIPTION=
  (ADDRESS=...)
  (CONNECT_DATA=(SERVICE_NAME=accounting.berlin.mycompany.de))))
```
Even if this entry would be given in the JDBC connection string - which service name would you use in Elastic? 

The only *true* solution I could find so far is using `SELECT * FROM global_name;` to get the fully qualified name of the database without assumptions about anything but of course this would be an oracle specific logic.

I hope you understand what I mean and I hope that I am not overcomplicating things...

**Comment by SylvainJuge** [comment]
Thanks for this very detailed explanation. No you're not over-complicating things, the things themselves are complicated !

While there could be many levels Oracle-specific magic involved, APM agent always has the perspective from the application.
- agent does not parse `tnsnames.ora` from filesystem, it just relies on the JDBC interface.
- if there is any load-balancing or indirection involved on DB side, then it's transparent to the application

In a way, it would be more or less like using DNS names vs actual network IP addresses, if there is any indirection, the app is not aware of it.

One nice thing with relying on `Connection#getCatalog` or `Connection#getSchema` is that we just reuse what the DB provides us, which saves us from painful parsing in case of Oracle.

On the other side, we already have some Oracle parsing for port number & host name, thus adding `service_name` or `sid` to this should not be that hard.

Since this issue was about `getCatalog` and `getSchema` and it's already a good first step, thus if you don't mind I think we'd better move this discussion to a new issue to populate `db.instance` from JDBC url parsing as a way to complement the quick-win we have with `getCatalog`.

**Comment by wolframhaussig** [comment]
> Since this issue was about `getCatalog` and `getSchema` and it's already a good first step, thus if you don't mind I think we'd better move this discussion to a new issue to populate `db.instance` from JDBC url parsing as a way to complement the quick-win we have with `getCatalog`.

Sure, no problem. Should I create a new one or are you able to split the existing discussion?

**Comment by SylvainJuge** [comment]
Here it is, I've just opened https://github.com/elastic/apm-agent-java/issues/1841
