### ISSUE TITLE
Can anybody help me understand why "tracestate" header is not doing what it's supposed to?

### ISSUE THREAD

**Issue by mdnhuda** [elastic/apm-agent-java#1804]
Reading the documents, I had the feeling that in order to have my transaction sampled, **traceparent** needs to have the sampled flag set, and **tracestate** dictates the sampling rate.
For example: 

```
traceparent: 00-ea79efa2f5134cf5a25b451c43358486-b1fc23eec24a4914-01
tracestate: es=s:0.01
```

However, it looks to me that as long as the sampled flag is set in the traceparent header, ElasticAPM is always recording the transactions, not just 1% of them.  (https://github.com/mdnhuda/elastic-apm-example/blob/master/docs/images/all_sampled_tracestate.png)

When I set '00' in the sampled flag, none of the requests are being sampled.

I am using elastic-apm-agent v1.21.0.

Can anyone help me figure out what I am doing wrong here?
I have setup a project to test this out here: https://github.com/mdnhuda/elastic-apm-example

**Comment by eyalkoren** [comment]
That is right for any service other than the first one creating the trace. The sampled flag dictates whether a trace should be sampled or not, based on the decision made by the initiating service. Whenever it is set, all downstream services will treat the transactions they create as sampled, regardless of the sample rate configuration. This ensures fully captured traces, rather than fragmented ones. See more details in [the docs](https://www.elastic.co/guide/en/apm/get-started/current/trace-sampling.html#_sampling_with_distributed_tracing).
The sample rate in the `tracestate` is used in order to extrapolate transaction counts whenever a rate lower than 1 is used.

I am closing this, as it is not a real issue. For general questions, please use [our forum](https://discuss.elastic.co/c/observability/apm/58).

**Comment by mdnhuda** [comment]
Thanks for clarifying @eyalkoren !
