### ISSUE TITLE
elastic apm java agent 1.17 and empty log4j2 log file

### ISSUE THREAD

**Issue by manikumarn** [elastic/apm-agent-java#1832]
We enabled elastic apm agent 1.17 in our Tomcat processes recently. After this we started seeing random cases of empty catalina.log files. Application generated log output were getting lost.

Environment:
* Tomcat
* Specify log4j2.xml using -Dlog4j.configurationFile system property. 
* The log4j2.xml specifies RollingFile Appender to rotate files on a daily basis.

It appears that a second instance of rolling file appender is instantiated when we enable 1.17 version of the agent. This was conflicting with the appender instance initialized in the context of the application. They both were stepping on each other leading to unreliable logging. 

This issue seems to be fixed in 1.23 of java agent.  Still logging it for information purposes as it took time to troubleshoot and relate the problem to apm-agent. The change lists associated with 1.23 indicate some logging related enhancements but nothing specific to this issue.

**Comment by SylvainJuge** [comment]
Hi @manikumarn, thanks for reporting this.

We usually advise to always use a recent version of the agent, and we should probably add it explicitly in the first things to check in the [Troubleshooting](https://www.elastic.co/guide/en/apm/agent/java/current/trouble-shooting.html) section of documentation, as it would could have saved you from all your debugging efforts.

The issue here is that there has been quite a lots of changes between 1.17.0 and 1.23.0, thus it would be quite hard to pinpoint the exact version that fixed this bug.
Also, given it's random that would be even more tedious and time consuming, thus I'm not sure it's worth investing time into it for something that appears already fixed.

As a result I will change our documentation with a proper paragraph into the Troubleshooting section, and close this issue once it's done.
