### ISSUE TITLE
apm-agent-parent uses a log4j version which is vulnerable

### ISSUE THREAD

**Issue by davescb1** [elastic/apm-agent-java#1873]
We are using apm-agent-attach v1.23.0 which internally uses elastic-apm-agent which references a log4j version that has a vulnerability 

<version.log4j>2.12.1</version.log4j>

See https://nvd.nist.gov/vuln/detail/CVE-2020-9488

Please help to update to the fixed version which is **2.13.2**

**Comment by eyalkoren** [comment]
This vulnerability is specific to the SMTP appender, which the agent does not use and since we relocate this log4j library packages, there is no risk that your application will use its SMTP appender by accident.
We would have gladly upgrade, but 2.12.1 is the latest one that is compatible with Java 7, with which we compile.

**Comment by eyalkoren** [comment]
@davescb1 in #1878 I made sure that in future releases we won't package the offending SMTP appender, to double-verify it cannot expose this reported vulnerability.
I hope this eliminates the related concern.

**Comment by davescb1** [comment]
thank you @eyalkoren
