### ISSUE TITLE
Support for negation in "trace-methods"

### ISSUE THREAD

**Issue by kamilwozniak4213** [elastic/apm-agent-java#2153]
## Is your feature request related to a problem?
We would like to be able to use the negation syntax in the [trace-methods](https://www.elastic.co/guide/en/apm/agent/java/current/config-core.html#config-trace-methods) config. This would allow us to only disable specific methods/classes and allow the rest.

## Describe the solution you'd like
For example in the properties file:

`trace_methods=!  org.springframework.*` or `trace_methods=not  org.springframework.*`

Best Regards

**Comment by SylvainJuge** [comment]
Hi @kamilwozniak4213 ,

The general use-case for `trace_methods` configuration option is to allow creating spans & transactions for frameworks and libraries that are not supported through automatic instrumentation. As such, this configuration should be used quite surgically and with limited scope, otherwise it can drastically increase overhead.

From the example that you provided, it looks like you are trying to use a very broad `trace_methods` parameter, and then ignore what does not seem relevant afterwards. This is clearly an anti-pattern and there are [better approaches to use here](https://www.elastic.co/guide/en/apm/agent/java/current/java-method-monitoring.html), for example using the async profiler allows to provide very good results without instrumenting every method and thus no overhead.

**Comment by SylvainJuge** [comment]
As you :+1: my previous response, I'll close the issue for now, we can definitely re-open it later if there is still a need for a change.

Just to be sure to properly understand, can you describe your use-case for using `trace_methods` here ?
- instrument a library/framework that is not currently natively supported through auto-instrumentation
- instrument a part of your application that needs to be monitored with dedicated spans/transactions: for example, custom batch execution, or internal delegation to a sub-component of the application.
- something else

**Comment by kamilwozniak4213** [comment]
@SylvainJuge  Yes, you can close it. Thanks for the advice and help!
