### ISSUE TITLE
connection pool  instrumentation

### ISSUE THREAD

**Issue by CoderLan0668** [elastic/apm-agent-java#2181]
`      conn=ds.getConnection();
	stmt=conn.createStatement();
	rset=stmt.executeQuery("select a.* from editor.cw_news a");
`
As the code above,  we had intrumented `stmt.executeQuery`, and we can get the time that the sql execution costs, 
but  we know nothing about `ds.getConnection()`, which often have a performance problem.

The problem also exists in the redis connection pool, why not make a pool plugin to help us solve these?

I found some issue , like #907 , #941 , but  it was created in 2019,. 

Is there someone still work on it?

**Comment by eyalkoren** [comment]
As you noted, we already have related issues, so I am closing this one as a duplicate.
If you have anything to add to #941, it would better be added as a comment on that issue, otherwise it's really difficult to collect all feedback.
I am not sure whether `Connection.createStatement()` is indeed interesting as a span, but if you have arguments that support that, they can be added there.

As long as we don't have such auto-instrumentation, did you consider using our [sampling profiler](https://www.elastic.co/guide/en/apm/agent/java/current/method-sampling-based.html) feature? Spans created by it are not considered for the span technology breakdown metrics, but it may still be very useful as it would highlight long-executing methods in slow transactions.

**Comment by eyalkoren** [comment]
@CoderLan0668 If you feel I miss something and this issue is about something else that should go separately from existing issues, please reopen and explain how this is different.
Thanks for the input either way!
