### ISSUE TITLE
How to disable elastic apm java agent using spring cloud?

### ISSUE THREAD

**Issue by sharanraj124** [elastic/apm-agent-java#2183]
I configured my spring boot app with elastic java agent. I have to disable my agent in spring cloud I didn't get any docs in your end.
I tried `enabled=false` also not working could you pls help us

**Comment by eyalkoren** [comment]
Sorry, I am not sure I get exactly what you are asking, but I'll try- take a look at the [configuration documentation](https://www.elastic.co/guide/en/apm/agent/java/current/configuration.html) to see what configuration methods and options are available for you.
For example, if you look at the [`enabled`](https://www.elastic.co/guide/en/apm/agent/java/current/config-core.html#config-enabled) option, you would see that it is not dynamic, meaning - it can only be set on startup, otherwise you need to use [`recording`](https://www.elastic.co/guide/en/apm/agent/java/current/config-core.html#config-recording) instead.
It also says that the config option name is `elastic.apm.enabled` if you set it as a system property and `ELASTIC_APM_ENABLED` if you set it as environment variable.

I hope this helps a bit. 

Either way, we typically use GitHub issues for verified bugs, enhancement requests etc. For general questions, please use our [forum](https://discuss.elastic.co/c/observability/apm/58) instead.

**Comment by sharanraj124** [comment]
Hi, I need clarification on how to disable the java APM agent in the spring cloud.

I am running java microservices with a single server and multiple apps.

I tried with recording=false, dynamically It won't work for me in my cloud. Locally working fine for me. If any extra configuration I need could help for us
