### ISSUE TITLE
Update log4j version

### ISSUE THREAD

**Issue by joshbressers** [elastic/apm-agent-java#2187]
We currently ship log4j version 2.12.1 in the java agent
https://github.com/elastic/apm-agent-java/blob/2e40422635e573bf83da84c67a325d2bf629a91a/pom.xml#L111

The version at the time of writing is 2.14.1. We should consider updating it to silence some security findings from vulnerability scanners.

**Comment by eyalkoren** [comment]
2.12.1 is the last version compiled with Java 7, so we cannot upgrade to a later version without dropping support for Java 7.
However, since we are not using the vulnerable appender (the SMTP appender), we made sure we don't package this appender though #1878, so that our users can feel safe to ignore related vulnerability reports.

I hope this safety measure is sufficient. Please close this issue if it is.
Thanks!
