### ISSUE TITLE
Status code sometimes is 200 instead of 500

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-agent-java#225]
Context: https://discuss.elastic.co/t/java-apm-agent-http-status-codes-not-correctly-identified/149156

Can also be reproduced when calling `/is-it-coffee-time` in opbeans-java

**Comment by eyalkoren** [comment]
I assume that the `service` method just throws an Exception, and lets the container handle it. If it is handled through a `ServletFilter`, than we should catch it, but maybe it redirects it to be handled by an error page (maybe even through `sendError`). 
Maybe monitoring `sendError` and `doFilter` would suffice, but I think a more bullet-proof way would be to keep a reference to the `Response` object on `service` and `doFilter` entry and instrument all those `HttpServletResponse` methods that cause a response commit (e.g. `flushBuffer` and maybe all the flushing methods in the OS/Writer related to the response).
PS - `sendRedirect` will also modify the response data, but I am not sure if it is normally called by container code or user code.
PS2 - the way to monitor the commit action would also be useful for other stuff, mainly those that enable monitoring and even modifying the response content (e.g. for automatic RUM agent injection to HTML)

**Comment by eyalkoren** [comment]
I would argue that not only we need to capture error status codes, we need to report them as errors actively (in addition to setting the status code in the `response` part of the transaction)

**Comment by eyalkoren** [comment]
Using @felixbarny example (`/is-it-coffee-time` in opbeans-java) as a test case, this is how Tomcat is handling errors thrown out of the user's servlet:
Following is the stack of where we end the transaction (at the end of the `doFilter` execution):
![transaction.end.png](https://zube.io/files/elastic/a343105e72532b7ddcf6eb68a466a38a-transaction-end.png)

At this state, the status code is still 200. Exception is caught and handled below on the stack, and only then status code is set:
![status-code-setting.png](https://zube.io/files/elastic/efd32ee83138a4b655d84078d5455857-status-code-setting.png)

Even if we instrumented this `setStatus` API, it would be too late, as we already ended the transaction.
In order to create a single transaction with our current model of execution, where the instrumentation of a single method is used for transaction start and end, we would have to implement a solution for Tomcat, meaning - a solution per app server probably. For example, the `CoyoteAdapter.service` at the bottom of the stack would be a perfect candidate, because it is a Servlet-API-like implementation of the `Servlet.service` method, only with `coyote` types rather than the standard API.

In order to solve this generically, we would probably need to introduce a different mode of transaction management, where the transaction is started somewhere and ended elsewhere. What we can do is start the transaction on the `doFilter`/`service` entry and wait for a later event to end it, when we know it is just the right time. Relying on `setStatus` is good, but assumes this is always called, which is not the case. Capturing all response commit event may be the most definitive generic way to capture such states, but we must capture **ALL** of them, otherwise we will get Transaction leaks.

**Comment by eyalkoren** [comment]
Decided to apply a simple fix for GA- before ending Servlet transactions, if Exception is not-null and status code is still 200 - setting the status code of the transaction response to 500.
A full blown solution may be implemented after GA.
