### ISSUE TITLE
Best practice for setting outcome

### ISSUE THREAD

**Issue by tobiasstadler** [elastic/apm-agent-java#2380]
Are there any best practices regarding setting outcome of a transaction/span?

Plugins often uses something like `.captureException(t).withOutcome(t != null ? Outcome.FAILURE : Outcome.SUCCESS)` to set. the outcome when ending a transaction/span. I wonder if the call to `withOutcome` is really necessary? Aren't `co.elastic.apm.agent.impl.transaction.Transaction/Span` using the same logic to determine the outcome in `beforeEnd` if the outcome isn't already set?

Are there any disadvantages in not using `.withOutcome(t != null ? Outcome.FAILURE : Outcome.SUCCESS` in a plugin and relaying on the logic in `co.elastic.apm.agent.impl.transaction.Transaction/Span#beforeEnd`

**Comment by eyalkoren** [comment]
The best practice is to set it through the plugin because this is the most definitive way for a plugin to set exactly what it wants. 

However:

> Are there any disadvantages in not using .withOutcome(t != null ? Outcome.FAILURE : Outcome.SUCCESS in a plugin and relaying on the logic in co.elastic.apm.agent.impl.transaction.Transaction/Span#beforeEnd

Not as long as the automatic outcome setting remains the same. I don't believe this logic is going to change dramatically, so I'd say it's safe to rely on it and slightly safer to set explicitly.

Closing this issue. Feel free to reopen if you want to continue this discussion.

**Comment by tobiasstadler** [comment]
Thank you for the explanation.
