### ISSUE TITLE
measuring the execution times of method invocation

### ISSUE THREAD

**Issue by WassimDhib** [elastic/apm-agent-java#239]
Hi,

I'm interested in measuring the internal beahvior of Java application.
One of the most common use cases is the measurment of methods execution duration.

Is it possible to specify in properties the app packages to be instrumented according to this logic ?
a method execution can be a span in global http transaction for example.

Thanks

**Comment by eyalkoren** [comment]
Hi and thanks for reaching out. 

This kind of instrumentation configuration is not possible.
If you're comfortable with writing code, you could subclass `ElasticApmInstrumentation` and apply instrumentation to all methods of all classes in a certain package (identified by name). If you are interested in doing that, you should probably get yourself familiar with ByteBuddy. 
Alternatively, you could use ByteBuddy, Spring AOP, or similar, for instrumentation and create those spans with [the public API](https://www.elastic.co/guide/en/apm/agent/java/current/public-api.html).

In addition, we do have plans to introduce [an annotation you can place on your methods so that spans are created for those methods](https://github.com/elastic/apm-agent-java/issues/212)

However, be aware that this is highly unadvisable to do so. As an APM agent, our instrumentation is intended to do much more that just timing, which means it will create a bigger overhead than required. Our mechanism is designed to enable tracing of specific functionalities, not for a broad range of classes/methods, so you should use it for collecting data from specific places of interest in your code. Maybe using a profiler would be more suitable for achieving what you want.

**Comment by WassimDhib** [comment]
Hi

I'll try with a custom instrumentation applied to a restricted set of application classes/methods.
I think the most of overhead comes from tracing/reporting.
If tracing is triggered from a high duration threshold, may be that will do the trick.

**Comment by eyalkoren** [comment]
Great. Good luck! After you set it up we will be glad to hear about your experience.

**Comment by eyalkoren** [comment]
Closing this issue - described what we can support at the moment in this regard.

**Comment by WassimDhib** [comment]
Thank you for the trace_methods option, it does exactly what I wanted to do.
