### ISSUE TITLE
Java Agent for lambda supports version java8-corretto? -Xshare:on

### ISSUE THREAD

**Issue by miltonhit** [elastic/apm-agent-java#2433]
Hello,

Since september 21 AWS depreciate java8-opendjdk from lambdas:
https://aws.amazon.com/pt/blogs/compute/announcing-migration-of-the-java-8-runtime-in-aws-lambda-to-amazon-corretto/

Today I tried to install apm-agent-java for lambda following this steps in this link:
https://www.elastic.co/guide/en/apm/agent/java/current/aws-lambda.html#aws-lambda-extension

Java Version: java8.al2 (Corretto)
Agent Version: elastic-apm-agent-1.28.4.jar

EnvVars:
AWS_LAMBDA_EXEC_WRAPPER: /opt/elastic-apm-handler
ELASTIC_APM_ENVIRONMENT: tst
ELASTIC_APM_LAMBDA_APM_SERVER: https://XXXXX.apm.us-east-1.aws.cloud.es.io:443
ELASTIC_APM_SECRET_TOKEN: XXXX

But I got this error in my cloudwatch log:
```
START RequestId: 8f939239-aa2a-4605-bdc6-0ffc7221811f Version: $LATEST
Picked up JAVA_TOOL_OPTIONS: -javaagent:/opt/elastic-apm-agent-1.28.4.jar
2022-01-28T13:56:07.450-03:00	An error has occurred while processing the shared archive file.
2022-01-28T13:56:07.450-03:00	Tool agent requires sharing to be disabled.
2022-01-28T13:56:07.450-03:00	Error occurred during initialization of VM
2022-01-28T13:56:07.450-03:00	Unable to use shared archive.
END RequestId: 8f939239-aa2a-4605-bdc6-0ffc7221811f
```
Researching I found that this JVM variable needs to be turned off and in this AWS implementation this does not happen:
```
-Xshare
```
In file "elastic-apm-handler" I found this bash script:
```
#!/bin/bash

export JAVA_TOOL_OPTIONS="-javaagent:/opt/elastic-apm-agent-1.28.4.jar ${JAVA_TOOL_OPTIONS}"

export ELASTIC_APM_SERVICE_NAME="${AWS_LAMBDA_FUNCTION_NAME}"
export ELASTIC_APM_AWS_LAMBDA_HANDLER="${_HANDLER}"
export ELASTIC_APM_METRICS_INTERVAL="0s"
export ELASTIC_APM_CENTRAL_CONFIG="false"
export ELASTIC_APM_CLOUD_PROVIDER="none"

exec "$@"
```

To perform a test I added a print in this var "$@" and I got this:
```
/var/lang/bin/java -XX:MaxHeapSize=1101005k -XX:MaxMetaspaceSize=157286k -XX:ReservedCodeCacheSize=78643k -XX:+UseSerialGC -javaagent:/var/runtime/amzn-log4j-security-jdk8-0.1alpha.jar -Xshare:on -XX:-TieredCompilation -Djava.net.preferIPv4Stack=true -classpath /var/runtime/lib/aws-lambda-java-core-1.2.0.jar:/var/runtime/lib/aws-lambda-java-runtime-0.2.0.jar:/var/runtime/lib/aws-lambda-java-serialization-0.2.0.jar lambdainternal.AWSLambda
```

note that there is the parameter -Xshare:on on exec script.
Just to perform a test, I made this change in the script:

```
NEW_EXEC_JAR=$(echo "$@" | sed 's/-Xshare:on/-Xshare:off/g')
exec $NEW_EXEC_JAR
```

It worked. Now my application is running but the APM is not being sent to the server due to this error: 
```
2022-01-28 18:43:19,979 [elastic-apm-server-healthcheck] WARN  co.elastic.apm.agent.report.ApmServerHealthChecker - Elastic APM server http://localhost:8200/ is not available (Connection refused (Connection refused))
```

I have other appliacations running in the same configurations of VPC/Networking using APM of elastic and all are working... Therefore I'm sure it's not a connectivity or network issue.

Now the main points are:

1. Can I do this?
2. Could this cause other problems in the AWS application or JVM?
3. Could this connection refused error be caused by this change?
4. Is this adaptation for this agent to work in java8-corretto foreseen in the roadmap?

Sorry if I was confused or rude, I don't usually write much here.
Thanks

**Comment by SylvainJuge** [comment]
Hi @miltonhit , thanks for filing an issue for this.

If I properly understand the main issue here:
- The agent works as expected with OpenJDK java 8, but it is being deprecated
- The agent does not work out of the box with newer Coretto java 8 runtime due to `-Xshare:on` JVM option.
- Modifying the JVM command to have `-Xshare:off` provides a temporary work-around with the Coretto java 8 runtime.

Once the agent is able to start, the `WARN  co.elastic.apm.agent.report.ApmServerHealthChecker - Elastic APM server http://localhost:8200/ is not available (Connection refused (Connection refused))` is expected as you have to either:
- use the lambda layer that allows to send data to APM server: https://github.com/elastic/apm-aws-lambda
- provide regular agent configuration through environment variables the APM server destination to use

Thus, if you don't mind I think here we should keep this issue focused on solving the main problem described above, and we can keep discussing any issues with APM configuration in the forum.

**Comment by SylvainJuge** [comment]
After further investigation I managed to reproduce it locally using AWS Corretto JVM `Corretto-8.322.06.2`.

`java -Xshare:on` will make the JVM load shared classes in memory from the JVM from the binary stored in `${JAVA_HOME}/jre/lib/amd64/server/classes.jsa`.

Using this feature seems incompatible with instrumentation agents, which makes sense as the binary representation of classes could be altered by the agent. This check happens early in the JVM startup even before the agent is started and even if the agent does not tries to modify any of the classes that might be included in the binary archive.

`java -Xshare:dump` will generate the `${JAVA_HOME}/jre/lib/amd64/server/classes.jsa` binary to then enable `-Xshare:on`.

`java -Xshare:off` will disable loading from the shared binary.

`java -Xshare:auto` will enable loading from the shared binary if the binary exists and it's possible, so if the `-javaagent` option is provided or the binary archive does not exists this will be equivalent to `-Xshare:off` and equivalent to `-Xshare:on` when no agent is present and the archive is available.

Thus we can conclude that the work-around that you have provided @miltonhit seems to be the right option for now.
We should modify the `elastic-apm-handler` file to include this until we have a better alternative.

One of the longer term implications of this could be that we might have to recommend switching to programmatic runtime attach instead of the `-javaagent` method, and the agent would be either packaged in the app as a dependency and unpacked at runtime, or kept within its own lambda layer.

**Comment by SylvainJuge** [comment]
@miltonhit I have added your work-around to the `elastic-apm-handler` script through #2438 .

In order to be sure it works as expected could you try to update your AWS layer with [this snapshot](https://apm-ci.elastic.co/job/apm-agent-java/job/apm-agent-java-mbp/job/PR-2438/2/artifact/src/github.com/elastic/apm-agent-java/elastic-apm-agent/target/elastic-apm-java-aws-lambda-layer-1.28.5-SNAPSHOT.zip) ? While not being a very permanent fix, it should make it easier to use until we have a better option here.
