### ISSUE TITLE
Add support of kafka batch consumer

### ISSUE THREAD

**Issue by Rez92** [elastic/apm-agent-java#2601]
## Is your feature request related to a problem?
when using Spring kafka batch listener (`batch = "true"` parameter), database requests are not captured by the java agent.
```java
@KafkaListener(topics = "${my-topic}", batch = "true")
public void consume(List<String> consumerRecords, Acknowledgment acknowledgment) {
    //SQL database requests are not captured
}
```
Note that when batching is disabled (`batch = "false"`) then database requests are captured by the java agent. 

## Describe the solution you'd like
Add kafka batch consumer tracing in order to capture database requests in `consumer` method.

## Describe alternatives you've considered
An alternative is to add `@CaptureTransaction` annotation on `consume` method.
```java
@CaptureTransaction
@KafkaListener(topics = "${my-topic}", batch = "true")
public void consume(List<String> consumerRecords, Acknowledgment acknowledgment) {
    //SQL database requests are captured
}
```

**Comment by eyalkoren** [comment]
This looks very relevant to #2489, which we are about to do.

I didn't try it out yet, but my assumption is that the Spring wrapper internally uses `org.apache.kafka.clients.consumer.KafkaConsumer`, which we do instrument. If that's true, the list accepted by this `consume` would be wrapped by our agent, thus creating Kafka transactions of the `messaging` type. 

Please provide some more info so we can look into that:
- Which exact Spring dependency are you using?
- Does the agent create Kafka consumer transactions of `messaging` type? 
- Please set the [`log_level`](https://www.elastic.co/guide/en/apm/agent/java/current/config-logging.html#config-log-level) to `debug` and provide a debug log that contains the agent startup and until a batch is accepted and processed. You can share such log through https://gist.github.com
-  Your proposed `@CaptureTransaction` alternative would create one transaction for the entire batch - would that be the ideal solution for you? The advantage is that the SQL query is captured within the batch processing, but the down side is that if you instrument with an APM agent the sender service/s, you would not get a single distributed trace for each send request. What tracing outcome would be ideal for your use case?

**Comment by Rez92** [comment]
- Spring dependencies : 
   - org.springframework.kafka:spring-kafka : 2.8.5
   - Spring boot : 2.6.6
 - Elastic APM version: 1.30.1
- Yes, the agent creates Kafka consumer transactions of `messaging` type but not database statement
-  Filtered [logs](https://gist.github.com/Rez92/f021bfb42d61399e7bd7bb92f12267b9)
- For each batch I have just one SQL insert query (batch insertion). Let's say I send 30 records in Kafka with `max-poll-records=10`. I will have 3 entry in `consume` method. I want to see in APM 3 samples and each one should contains the kafka messaging and the database query. This is what I have when adding `@CaptureTransaction` annotation. I tested this locally with Fleet in Kibana.

**Comment by eyalkoren** [comment]
Thanks for the useful info!
You can follow #2610 .
What we plan to do now is change our Kafka instrumentation, so that in your case, once you add the manual `@CaptureTransaction`, you would get exactly what you want, but in addition, we will add links to the sending spans, in case you also have APM agent on the record sending service/s. The current plan is to create a span (child of the batch transaction) for each record with a link to the sender span. Another option is to not create a span per record, but to add span links for all batch records (10 in your case) to the enclosing transaction. What would you say better serves your use case?

As for automatic instrumentation of the Spring wrapper, I am not sure about that. If we add it, then we make the decision for our user to have single batch-processing transaction instead of transaction per record. The fact that it is so easy to get it done just by adding a single annotation makes me wonder if it will improve the automatic result for most users or not. I think of existing Spring-Kafka users who are now happy with their transaction-per-record state. These will get different tracing behavior if we add the instrumentation you requested after they upgrade the agent.
