### ISSUE TITLE
Jedis 4 support?

### ISSUE THREAD

**Issue by spmason** [elastic/apm-agent-java#2616]
I tried upgrading my application to Jedis v4 and lost all Redis time from my application traces

Which makes sense, as according to https://www.elastic.co/guide/en/apm/agent/java/current/supported-technologies-details.html#supported-databases APM only supports up to Jedis 3.x

Are there any plans to support Jedis 4? It was first released back in December, and in [the release notes for 3.8.0](https://github.com/redis/jedis/releases/tag/v3.8.0) they declare that as the last release on the 3.x line, so it will not be getting updates any more

**Comment by eyalkoren** [comment]
Thanks for reporting!
I tried something in #2626. Please try [this agent snapshot](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-java%2Fapm-agent-java-mbp/detail/PR-2626/1/artifacts) and let us know if it works for you.

**Comment by spmason** [comment]
Thanks @eyalkoren! I've deployed this to our test cluster and it seems to be working well - Redis time is now shown properly in the timeline with Jedis 4

**Comment by spmason** [comment]
Thanks. Our Jedis 4 upgrade is actually dependant on a bigger refactoring of our Redis use that needs to go out first, so it'll be a little while before I'll be able to do more extensive testing of this. I'll keep you informed

**Comment by eyalkoren** [comment]
What I did in #2626 is change the way we instrument Jedis for all versions, so that it is simpler and also more suitable for Jedis 4.
So actually, if you are using older Jedis (and Redis) versions across your services along with Elastic Java agent, then trying the provided snapshot on them and comparing with tracing produced by the existing agent, would provide an even better indication that this change is good 🙂

**Comment by eyalkoren** [comment]
Version [1.31.0](https://www.elastic.co/guide/en/apm/agent/java/current/release-notes-1.x.html#release-notes-1.31.0) has been released with Jedis 4.x support.
