### ISSUE TITLE
[DOCS] Add ES Java API Client to list of supported technologies

### ISSUE THREAD

**Issue by n0othing** [elastic/apm-agent-java#2625]
The Elastic Java APM agent supports both the ES Java REST client and the new Java API client. It'd be helpful to mention both in the supported technologies section of the docs https://www.elastic.co/guide/en/apm/agent/java/current/supported-technologies-details.html#supported-databases.

> The agent automatically creates Elasticsearch spans for queries done through the official REST client.

**Comment by eyalkoren** [comment]
There is already work in progress to add tests for the new ES Java client (#2211), which was blocked for some time due to incomplete support of `msearch` queries.
As long as we don't have this continuously tested, we cannot add it to the docs.
I added a task to #2211 to make sure we document the official support as part of it, so I am closing this one.
If you think I missed something or this issue is still required, please reopen and explain.
Thanks.
