### ISSUE TITLE
APM agent support JBOSS EAP 7.1 

### ISSUE THREAD

**Issue by elisanotarangelo** [elastic/apm-agent-java#2645]
Having the apm server version 7.12.1 and java application 1.30.0 is JBOSS EAP 7.1 supported? 
Because it does not currently log transactions, I wanted to find out if it is an incompatibility problem or there is a configuration error.
Thank you

**Comment by eyalkoren** [comment]
Thanks for reaching out.
We tend to use GitHub issues for actually known issues, rather than questions and clarifications.
JBoss EAP 7.1 is [supported](https://www.elastic.co/guide/en/apm/agent/java/current/supported-technologies-details.html#supported-app-servers).
If you installed the agent [as instructed ](https://www.elastic.co/guide/en/apm/agent/java/current/setup.html) and it doesn't work, your first place to look is our [documentation](https://www.elastic.co/guide/en/apm/agent/java/current/index.html) in general and the [troubleshooting page](https://www.elastic.co/guide/en/apm/agent/java/current/trouble-shooting.html) specifically.
If you can't figure it out though logs and other means, please reach out through our [forum](https://discuss.elastic.co/c/observability/apm/58) instead with as much information as possible, including a relevant log, preferably in `debug` level.
I am closing the issue for now and if it turns out there is an issue indeed, we can then reopen.

**Comment by elisanotarangelo** [comment]
EJB version 3  is supported?

**Comment by elisanotarangelo** [comment]
@eyalkoren Thanks for the indications, but checking the documentation and the current configuration the problem persists, only the compatibility with JBOS EAP is indicated, but it does not say if the EJBs are compatible

**Comment by SylvainJuge** [comment]
We only list what is supported, we don't support EJBs nor RMI (the protocol it relies on).
There are a few posts in the forum like [this one](https://discuss.elastic.co/t/apm-data-not-coming-in-kibana-for-jboss-eap-running-on-wildfly-using-ejb-instead-of-http/250467) that explain in more detail the alternatives, in this case using the agent [Public API](https://www.elastic.co/guide/en/apm/agent/java/current/apis.html) and manual instrumentation is probably the best option.
