### ISSUE TITLE
If I use attach model, what do I need to pay attention to.

### ISSUE THREAD

**Issue by lobsterHe** [elastic/apm-agent-java#2725]
If I use attach model, what do I need to pay attention to?
how to attach docker pid? i need deploy elastic-apm in docker？
i want to deploy in linux and attach java processes running in docker containers,but failed.

**Comment by eyalkoren** [comment]
We typically use GitHub issues for verified bugs, enhancement requests etc. For general questions, please use our [forum](https://discuss.elastic.co/c/observability/apm/58) instead.

To answer some of your questions:

> If I use attach model, what do I need to pay attention to?

Take a look at the relevant [documentation](https://www.elastic.co/guide/en/apm/agent/java/current/setup.html). One thing to notice is that with the runtime attachment, you may lose some traces until the agent gets fully attached.

> how to attach docker pid?

Runtime attachment is not supported from outside of running containers, because the underlying technology has limitations in that regard.

> i need deploy elastic-apm in docker？

If you mean deploying an APM Server, then you may, but you don't need to. If you do, you need to enable communication from the container to your Elasticsearch cluster. If you don't, you'd need to enable communication from your app to the APM Server. Probably the simplest way would be to create an Elastic cloud deployment that includes an APM Server and only adjust your images to include the agent and refer to it through the `JAVA_TOOL_OPTIONS` env variable or add it to the application command line.

If you orchestrate your containers through k8s, you may want to look into this [blog post](https://www.elastic.co/blog/using-elastic-apm-java-agent-on-kubernetes-k8s). Even if not, it can give you a sense of what's required.

**Comment by lobsterHe** [comment]
Thanks for your reply.
