### ISSUE TITLE
Option to sample transaction creation

### ISSUE THREAD

**Issue by fgabolde** [elastic/apm-agent-java#2949]
The current `transaction_sample_rate` does not seem to cause fewer transactions to be captured:

> We still record overall time and the result for unsampled transactions, but no context information, labels, or spans.

The tuning docs are misleading on this topic and should possibly be reworded:

> Sample rate is the percentage of requests which should be recorded and sent to the APM Server.

For a specific HTTP application of ours, which already does not emit any spans (because there are no instrumented methods, automatically or otherwise), `transaction_sample_rate` did not result in any fewer events being sent to the APM server (because they were already all transactions). We are still interested in the `http.request.*` metadata but we could deal with having it for e.g. 10% of the incoming traffic.

This application has fairly high traffic and our small-ish Elastic cluster is having issues as a result.

How can we configure the APM agent so that fewer transactions will be sent to the server?

**Comment by jackshirazi** [comment]
Thanks. The agent handles this slightly differently for different server versions. Prior to 8.0, the transaction data is sent but drops contextual information to reduce the transfer and storage size of the trace. From 8.0 the transactions should be dropped by the agent and no transfer should happen.

If the transactions are dropped entirely for pre-8.0 servers, the statistics and charts would display incorrect data because they aren't prepared for that, they use the non-dropped transactions for the stats. I wouldn't recommend doing so. If upgrading to the latest server version is not possible and you nevertheless want to try your agent with dropping those transactions, it's perfectly possible for you to fork the agent or add a community plugin which can force that ([eg changing this method](https://github.com/elastic/apm-agent-java/blob/14919fe320dbaf88518d990b548ddd41d4b4ef97/apm-agent-core/src/main/java/co/elastic/apm/agent/report/ApmServerClient.java#L342))

You're right the documentation is a little misleading for pre-8.0 server, I'll change it to make it clearer

**Comment by fgabolde** [comment]
> The agent handles this slightly differently for different server versions

Oh, OK, I did not realize this could be a thing! Yes it probably warrants some mention in the docs.

Are there other differences in agent behavior depending on the target APM server?

**Comment by jackshirazi** [comment]
All related to comms protocol, statistics, or improved/additional server features like span compression

**Comment by fgabolde** [comment]
Thanks @jackshirazi.
