### ISSUE TITLE
[DOCS] AWS Lambda doc improvements

### ISSUE THREAD

**Issue by lucabelluccini** [elastic/apm-agent-java#2969]
The documentation page [AWS Lambda setup](https://www.elastic.co/guide/en/apm/agent/java/master/aws-lambda.html#_step_3_configure_apm_on_aws_lambda) might benefit of a "warning" message about the fact the wrapper script sets `ELASTIC_APM_AWS_LAMBDA_HANDLER` to the value of `_HANDLER` (`AWS_LAMBDA_HANDLER`). This might end up into confusion as the user might think they're using the correct handler, but they're not.

The documentation page [serverless](https://www.elastic.co/guide/en/apm/agent/java/master/config-serverless.html#config-aws-lambda-handler) might benefit of additional insights regarding the fact the class has to implement specific interfaces in order to be auto-instrumented.

**Comment by AlexanderWert** [comment]
> The documentation page [AWS Lambda setup](https://www.elastic.co/guide/en/apm/agent/java/master/aws-lambda.html#_step_3_configure_apm_on_aws_lambda) might benefit of a "warning" message about the fact the wrapper script sets ELASTIC_APM_AWS_LAMBDA_HANDLER to the value of _HANDLER (AWS_LAMBDA_HANDLER). This might end up into confusion as the user might think they're using the correct handler, but they're not.

I think we rather should fix our wrapper script, so that when `ELASTIC_APM_AWS_LAMBDA_HANDLER` is set explicitly in the env vars the script does NOT overwrite that value.

> The documentation page [serverless](https://www.elastic.co/guide/en/apm/agent/java/master/config-serverless.html#config-aws-lambda-handler) might benefit of additional insights regarding the fact the class has to implement specific interfaces in order to be auto-instrumented.

The handler does need a specific interface only if context info needs to be collected (e.g. SQS context, API Gateway, etc.). But the auto-instrumentation is always applied, independent of the interface of the handler.

But I agree that we should improve our documentation to make this second point clearer.
