### ISSUE TITLE
JAX-RS Annotation on interface instead of implementation produces a generic request name

### ISSUE THREAD

**Issue by simonlg** [elastic/apm-agent-java#341]
**Describe the bug**
When the jax.ws.rs.Path annotation is on an interface instead of an implementation, the request name is filled with a generic value of ServletContainer#doPost or ServletContainer#doGet instead of the Classname#Methodname

**To Reproduce**
1. Create a resource with @Path annotation on the interface
2. Do not set any annotations on the implementation
3. Query the API
4. See the generic request name within the APM event

**Expected behavior**
I expect to see the Classname#MethodName

After fast investigation, within the JaxRsTransactionNameInstrumentation class, instead of using ElementMatchers.isAnnotatedWith(named("javax.ws.rs.Path")), try using ElementMatchers.inheritsAnnotation(named("javax.ws.rs.Path")). I may work.

**Comment by eyalkoren** [comment]
@simonlg thanks for trying out the agent and providing this useful feedback.
Since the JAX-RS 2.0 spec (section 3.6 Annotation Inheritance) says: 
> Note that inheritance of class or interface annotations is not supported.

we decided not to support such inheritance, even though we are aware that Jersey DOES support it. The reason for this decision is performance- checking existence of annotation on the entire hierarchy of each class can delay application start time considerably. Since we later decided to limit the entire JAX-RS annotation lookup only to classes included in the configured `application_packages` (see [in our documentation](https://www.elastic.co/guide/en/apm/agent/java/master/config-stacktrace.html#config-application-packages)), we may revisit this decision in the future and see if it makes sense to remove this limitation.
However, if the spec says this is not supported, maybe best practice would be to explicitly define the annotation within the implementing classes.

**Comment by simonlg** [comment]
@eyalkoren If the best practice is to explicitly define them in the implementing classes, I will adjust my code.

Thank you for the prompt response!
