### ISSUE TITLE
Elastic APM Java agent cannot automatically infer the class name / object name for a span when using Scala and @CaptureSpan

### ISSUE THREAD

**Issue by georgms** [elastic/apm-agent-java#3686]
## Describe the bug

According to the documentation [`@CaptureSpan` will automatically set the name of the span to `Classname#methodname`](https://www.elastic.co/guide/en/apm/agent/java/current/public-api.html#api-capture-span). When using Scala 2, this works fine for classes but not for objects. For objects, only the `#methodname` is inferred but the `Classname` is just missing.

## Steps to reproduce

1. Use Scala 2.12.18 and `co.elastic.apm:apm-agent-api:1.50.0`.
2. Create a Scala class and object:
 ```scala
import co.elastic.apm.api.{CaptureSpan, ElasticApm, Transaction}

class Example {
  @CaptureSpan
  def myClassMethod() = println("Example#myClassMethod")
}

object Example {
  @CaptureSpan
  def myObjectMethod() = println("Example#myObjectMethod")
}

ElasticApm.startTransaction()

(new Example).myClassMethod()

Example.myObjectMethod()

ElasticApm.stopTransaction()
```
3. Run the code.
4. Check your Elastic APM instance for the captured spans.

## Expected behavior

Two spans are captured with the names:
1. `Example#myClassMethod`
2. `Example#myObjectMethod`

## Debug logs

n/a

**Comment by jackshirazi** [comment]
Hi, thanks for reporting this. Unfortunately we're short of Scala experience at this time, so we're unlikely to priortize working on this soon.

**Comment by wolframhaussig** [comment]
I haven't used Scala, but here is what I think happens:
[This article](https://www.toptal.com/scala/scala-bytecode-and-the-jvm) explains in the chapter "Function as Value" what is being generated by the Scala compiler:
- an `Example` class as a wrapper
- an `Example$` class for the `object`
- an `Example$anonfun$1` for the method within

If I am not mistaken, the issue is with the code in `SimpleMethodSignatureOffsetMappingFactory`:
```java
final String className = instrumentedMethod.getDeclaringType().getTypeName();
String simpleClassName = className.substring(className.lastIndexOf('$') + 1);
```
This code was made for nested classes where the text after the dollar sign denotes the class name of the nested class. In the case of scala, this string is empty, therefore the class name in APM is empty.

Maybe it would be possible to check the class name for an empty string and use the parent class name in this case?

**Comment by wolframhaussig** [comment]
@jackshirazi I added a draft PR - maybe you could check sometime if this is the correct direction?
