### ISSUE TITLE
Support  the container of Weblogic and JBoss.

### ISSUE THREAD

**Issue by GHjyzhou** [elastic/apm-agent-java#387]
At present, the container of Weblogic and JBoss is not supported. Can you consider the follow-up support?

**Comment by felixbarny** [comment]
Hi, there are already some issues tracking support for JBoss and WebLogic.
 * https://github.com/elastic/apm-agent-java/issues/109
 * https://github.com/elastic/apm-agent-java/issues/163

We first need to set up a testing environment with the appropriate licenses in order to be able to test WebLogic and JBoss as part of our continuous integration. Unfortunately, there are no easy-to-access docker containers with a development license available. That's why it's taking a bit longer to support these servers.

Which versions of these servers are you using? If you are using a recent JBoss EAP version, the agent should probably work, as it's based on WildFly, which we do support. But we can't support it officially until we have added it to our CI.
