### ISSUE TITLE
Support JDK6 AND Servlet2.5

### ISSUE THREAD

**Issue by langyan1022** [elastic/apm-agent-java#402]
**Is your feature request related to a problem? Please describe.**
Support JDK6 AND Servlet2.5
**Describe the solution you'd like**
Hi.
Can you consider supporting JDK6 AND Servlet2.5.
After all, there are still some old projects that are using these two technologies, and for some reason they cannot be upgraded or the upgrade costs are too high.
I found another project using the javaagent and using bytebuddy apache skywalking agent to support jdk6.

**Comment by eyalkoren** [comment]
Thanks for your input. We are very sorry to hear we cannot support parts of your code base. 

Like any cost/value weighing process, deciding where to start our support is a matter of figuring out how much it costs to support a technology vs how widely it is being used. Based on those, we decided our minimum version for Java would be 7 and minimum version for Servlet API would be 3.

What I can suggest is that you use our solution for anything you can in order to benefit from the entire Elastic stack goods, and use some other OpenTracing-complying agent for your Java6/Servlet2.5 app. For example, it looks like there is an [OpenTracing implementation for SkyWalking](https://github.com/apache/incubator-skywalking/blob/master/docs/en/setup/service-agent/java-agent/Opentracing.md). If you do that, switching to using our agent will be very easy once you upgrade to higher Java and Servlet API.

I am closing this issue. Please ask us further questions in [our discuss forum](https://discuss.elastic.co/c/apm).
