### ISSUE TITLE
check server version on startup

### ISSUE THREAD

**Issue by wolframhaussig** [elastic/apm-agent-java#687]
As discussed in elastic support ticket 00352713 I open this feature request.

**Is your feature request related to a problem? Please describe.**
Last week I fell into the trap of addLabel for numbers and booleans requiring APM server 6.7 where we currently use 6.5.4. I find it unfortunate as the [comatibility page](https://www.elastic.co/guide/en/apm/get-started/current/agent-server-compatibility.html) says that the agent requires 6.5 or higher. In my mind compatible means that the server can import any data received from the agent(even if he ignores some fields). This is not the case as the server rejects any document from the agent if addLabel with numbers or booleans are used:
2019-06-18 14:19:07.606 [apm-reporter] WARN co.elastic.apm.agent.report.IntakeV2ReportingEventHandler - {"accepted":155,"errors":[{"message":"Problem validating JSON document against schema: I[#] S[#] doesn't validate with \"transaction#\"\n I[#] S[#/allOf/0] allOf failed\n  I[#/context/tags/JOBS_FOUND] S[#/allOf/0/properties/context/properties/tags/patternProperties/%5E%5B%5E.%2A%22%5D%2A$/type] expected string or null, but got number","document":...

**Describe the solution you'd like**
It would be great if the agent could check the server version on start and make the data compatible. In my example: Instead of sending the labels as numbers and booleans convert them to strings first.

Maybe you can even write a warning once into the log file?

**Describe alternatives you've considered**
Modifying the code would fix this problem, but this would mean that the new features cannot be used in environments with the newer APM server version.

**Comment by eyalkoren** [comment]
Thanks for reporting.

>Instead of sending the labels as numbers and booleans convert them to strings first

The idea of Labels is providing a way to store data that is indexed, therefore searchable and aggregate-able. If you would think this is what you achieve by sending a Number label, and we would instead index it as text, I don't think that would be a good experience for you once you try to query them. 

So, I believe it is better to get an error somewhere, either on server or agent. Currently you get the error on the server, which was useful enough to make you understand what the problem is.
I agree it would be nicer get a more informative logging message on the agent side. We will think whether we want to get into this versioning logic.

**Comment by wolframhaussig** [comment]
I would even agree with dropping the labels completely. My point is: currently the server cannot even import the data so all Spans with those labels are not visible in Kibana APM UI.
