### ISSUE TITLE
Add a build tool which does nullability checks

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-agent-java#7]
Other code quality tools might also be interesting, but I had bad experiences with most of them in terms of an overwhelming amount of false-positives.

**Comment by alvarolobato** [comment]
Findbugs usually works well, the problem is they have deprecated it in favor of [JSR-305](https://jcp.org/en/jsr/detail?id=305) which is not published and in status `dormant`. Not being published affects the licensing in some situations [for non OSS software](https://stackoverflow.com/a/36198568). I've seen many OSS projects use it, it should be fine.
