### ISSUE TITLE
ApmScopeManager.active() is returning scope with finishSpanOnClose always set to false

### ISSUE THREAD

**Issue by jzhn** [elastic/apm-agent-java#703]
**Describe the bug**
Based on the code: https://github.com/elastic/apm-agent-java/blob/master/apm-opentracing/src/main/java/co/elastic/apm/opentracing/ApmScopeManager.java#L58-L67, when the app gets the current active scope from APM tracer like this:
```
Scope scope = tracer.scopeManager().active();
```
the returned `scope` object always has `finishSpanOnClose` set to false, if we close the scope, the current span inside scope is not finished. 
This is causing spans created by [opentracing/java-spring-messaging](https://github.com/opentracing-contrib/java-spring-messaging/blob/master/opentracing-spring-messaging/src/main/java/io/opentracing/contrib/spring/integration/messaging/OpenTracingChannelInterceptor.java#L84-L96) being dropped.

**To Reproduce**
This issue can be simply reproduced by debugging the below snippet:
```java
Tracer tracer = new ElasticApmTracer();
tracer.buildSpan("test")
  .startActive(true);
Scope scope = tracer.scopeManager().active();
// verify that finishSpanOnClose is false.
scope.close();
```
Or it can be reproduced end-to-end by having a spring-cloud-stream app with [opentracing/java-spring-messaging](https://github.com/opentracing-contrib/java-spring-messaging). The spans produced by the library is not shipped to Elastics.

**Expected behaviour**
`tracer.scopeManager().active()` returns a `Scope` object that preserves the `finishSpanOnClose` config from current active scope.

**Comment by eyalkoren** [comment]
Thanks for reporting.
Looking into this.

**Comment by eyalkoren** [comment]
The challenge is to make sure `tracer.scopeManager().active()` reflects the internal agent active stack in order to **allow inherent agent tracing to coexist with OT tracing**. 
In other words, consider this (valid) scenario:
```
// traced through OpenTracing
void f1() {
    try (Scope scope1 = co.elastic.apm.opentracing.ElasticApmTracer.buildSpan().startActive()) {
       f2();
    }
}

// traced not through OpenTracing
void f2() {
    // create and activate internal span (eg some auto-instrumented framework)
    Span internalSpan = co.elastic.apm.agent.impl.ElasticApmTracer.createSpan().activate();
    f3();
    internalSpan.end().deactivate();
}

// traced through OpenTracing
void f3() {
    Scope scope2 = co.elastic.apm.opentracing.ElasticApmTracer.scopeManager().active(); 
    Span otSpan = co.elastic.apm.opentracing.ElasticApmTracer..buildSpan().asChildOf(scope2.span()).start();
} 
```
In this case, we expect `scope2` (in `f3`) to represent the currently active `internalSpan` (created in `f2`), which is why we must create a new `Scope` instance. If we ignore internal spans and instead return the active OpenTracing scope, `otSpan` will be reported as the child of the `f1` span, which is wrong.

I will try to address that by maintaining an OpenTracing active `Scope` stack, that will only be used to return the same scope instance when invoked in the same stack state, otherwise return a new scope instance.

This will still not work if some OpenTracing tracing code is not being managed properly in terms of stack state, thus attempting to close a scope that it did not create.

**Comment by eyalkoren** [comment]
@jzhn Can you please download and try out [this bugfix snapshot build](https://apm-ci.elastic.co/job/apm-agent-java/job/apm-agent-java-mbp/job/PR-709/1/artifact/src/github.com/elastic/apm-agent-java/elastic-apm-agent/target/elastic-apm-agent-1.7.1-SNAPSHOT.jar) and see if it fixes the problem?

**Comment by jzhn** [comment]
@eyalkoren : Thanks for the quick response!

Looks like you modified both APM agent and apm-opentracing library. I built apm-opentracing locally from your branch as well.

With the APM agent provided above, and the locally built apm-opentracing library, I'm able to verify that `finishSpanOnClose` is properly preserved, and the span is being shipped to Elastics. There's another minor issue of opentracing/spring-messaging [related to the usage of `FOLLOWS_FROM` reference](https://github.com/opentracing-contrib/java-spring-messaging/blob/master/opentracing-spring-messaging/src/main/java/io/opentracing/contrib/spring/integration/messaging/OpenTracingChannelInterceptor.java#L62), but I understand that it's well documented that APM only supports `CHILD_OF`. As far as this issue, I think the fix looks good. 👍

**Comment by eyalkoren** [comment]
> Looks like you modified both APM agent and apm-opentracing library. I built apm-opentracing locally from your branch as well.

Right, forgot to upload it as well, sorry about that 🤦‍♂ .

> There's another minor issue of opentracing/spring-messaging related to the usage of FOLLOWS_FROM reference, but I understand that it's well documented that APM only supports CHILD_OF

We are now doing an assessment of what we need to do in order to provide a more "wholistic" support for messaging frameworks and this may be one of the topics we need to look at.

Thanks for the feedback and fix verification!

**Comment by felixbarny** [comment]
Note that the `finishSpanOnClose` flag is deprecated in recent OT versions. Not sure if it makes sense to put effort in a deprecated feature. It's probably a better idea to contribute to https://github.com/opentracing-contrib/java-spring-messaging so that it does not use the deprecated flag anymore.

**Comment by jzhn** [comment]
@felixbarny : you are right, thanks for pointing that out!

@eyalkoren : sorry for wasting your time for supporting deprecated methods. I'll create an PR to update java-spring-messaging instead.

**Comment by eyalkoren** [comment]
@jzhn please note we will not merge our fix.
Did you create a PR for stop using the deprecated API?
