### ISSUE TITLE
[docs] Clarify use of application_packages config settings

### ISSUE THREAD

**Issue by roncohen** [elastic/apm-agent-java#726]
We're getting a lot of question about what the application packages setting does and it seems users are having trouble understanding the purpose of it. Clarifying the purpose and adding examples should help reduce the confusion.

https://www.elastic.co/guide/en/apm/agent/java/current/config-stacktrace.html#config-application-packages

cc @bmorelli25

**Comment by felixbarny** [comment]
See also my answer on https://discuss.elastic.co/t/apm-java-jboss-doubt-related-application-packages/190707. Maybe we can use a Brandonified version of that.

However, ideally, we should also think about options on how to automatically infer that so that users don't need to configure it at all or that we don't need to recommend and promote setting the option anymore.

For example, we could detect the application class loader and treat classes loaded from there as application classes. We need to find a way to distinguish them from libraries which may be loaded from the same class loader but mostly from a different jar file.

**Comment by bmorelli25** [comment]
I will attempt to Brondonify™ this and open a PR
