### ISSUE TITLE
packer_cache is failing

### ISSUE THREAD

**Issue by nik9000** [elastic/apm-agent-java#805]
It looks like your packer_cache script is currently failing:
```
Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.19.1:verify (default) on project apm-jdbc-plugin: There are test failures.
```

Is there any chance you could not run tests in that script? That doesn't seem like something that makes sense to do while building the nodes that'll run your CI. When they fail they make a huge, huge mess of my CI reports. Just red logs everywhere.

**Comment by felixbarny** [comment]
The tests are executed so that all maven dependencies and, more importantly, all docker containers are cached. We use Testcontainers which integrate into our testing and download docker containers while running the tests. So we'd really like to continue doing that.

**Comment by nik9000** [comment]
It makes debugging these failures super difficult though. Is there any way to ask test containers to download what it needs explicitly? I see packer cache script failing because of test failures and I think "APM team needs to fix their test" not "there is missing docker container".

**Comment by v1v** [comment]
If I understood correctly the packer cache script should not fail in the maven step (see https://github.com/elastic/apm-agent-java/blob/a2d6063d0a2cd7f90caf1d28682ca6bdfc3d9609/.ci/packer_cache.sh#L4) otherwise if the build fails, as it happens now, the docker images pull steps won't be updated and therefore the build times will be increased.

So, I'd suggest avoiding failing the script for the nature of what the script should care about.
