### ISSUE TITLE
Improving documentation - stop using "incubating" and explain the expectations

### ISSUE THREAD

**Issue by fstendel** [elastic/apm-agent-java#876]
**Is your feature request related to a problem? Please describe.**
JMS instrumentation of ElasticAPM Java agent is marked as "in incubating" since version 1.7.0,
leaving developers with a lot of uncertainty in regards to production readiness. 
Additionally, - even when uncertainty is put aside - this instrumentation is activated by "not deactivating any other instrumentation" leading to situations where one could not use the "incubating" JMS-instrumentation, e.g. when another instrumentation needs to be deactivated.  

**Describe the solution you'd like**

- Clarification in the documentation about what incubating means.
- Ideally an ETA when feature leaves this state.
- Separate configuration key to explicitly activate incubating features (e.g. enable_incubating_features=jms). A sensible default behavior in regards to incubating state change would be to ignore this particular entry when features leave incubating and print out a warn-message in the logs.

**Describe alternatives you've considered**
The alternative considered and currently in-place is to implement some sort of decorator-class which resembles the behavior of the JMS-instrumentation in question (e.g. decorator for MessageListener).
As this decorator only resembles the behavior of the ElasticAPM-instrumentation, both the incubating instrumentation and the homegrown solution might diverge from a UI-users perspective.

**Comment by felixbarny** [comment]
Thanks for the issue, @eyalkoren will get back to you soon.
I like the idea of a flag to enable incubating features.

**Comment by eyalkoren** [comment]
Thanks for the questions and suggestions. I completely agree we can improve both the configuration and the documentation of incubating features. 
Since this is not specifically about JMS, I will change this issue's title so we can use it for these improvements. I hope this is OK.

> JMS instrumentation of ElasticAPM Java agent is marked as "in incubating" since version 1.7.0,
leaving developers with a lot of uncertainty in regards to production readiness.

This uncertainty is "a feature" of incubating/experimental features. It gives us a way to do things incrementally and let early-adapters try it out and provide feedback. The (currently undocumented) "contract" of using those, is that they may change behavior or configuration over time. It is not so much about stability, we are implementing these features with the same caution and care, but we may be a bit more "bold" in testing assumptions 🙂 . The general recommendation is to test everything on your dev/staging env before moving to production, and this is more true with incubating features.
With regards to JMS- this is the first support we have for messaging systems in our APM product, so there are stuff we need to finalize across our entire APM solution going forward. For example, transaction types or span names may change in the next version and there are fields we will soon add to messaging documents, so the data it produces will change. Another example is the default behavior for the `receive` APIs instrumentation, which is going to change in future release. Whenever we feel such changes may be frequent, we need to make users aware, and we use the `incubating` flag for that.

> Additionally, - even when uncertainty is put aside - this instrumentation is activated by "not deactivating any other instrumentation" leading to situations where one could not use the "incubating" JMS-instrumentation, e.g. when another instrumentation needs to be deactivated.

I guess this is also the fault of our documentation- you can deactivate any instrumentation group from the documented list. The only one that is deactivated by default is `incubating`, but you can override that with whatever list you want, so this is certainly possible. What's **not** possible is selecting specific incubating groups, which your suggestion can fix, but I don't think this is currently a real problem.

**Comment by fstendel** [comment]
Hi,

I'm completely fine regarding the renaming :). 

Regarding your paragraph about what incubating means:

I'm aware that you guys are doing a pretty good job over there!

But just speaking from a customers perspective it's actually hard to tell what 'incubating' means to you guys right from the documentation (as other vendors/projects might have other definitions in that mean). E.g.: 
- Changing transaction or span names --> fine, one can deal with it on version changes
- Missing Integration in various other soultion --> fine, it's pretty usual when new feature-sets lacking a 'full integration'
- known shortcomings, like for instance security problems/race conditions in 'usual use cases' --> hell no, that's not something I would want to use in production (even if I know its working)

Said that, it would be nice if it's actually stated somewhere in the documentation what I - as a customer - have to be aware of/deal with when using incubating features.


About the configuration:

Lets say I develop a software component, where I need to deactivate the JDBC-Plugin/Instrumentation (e.g. if I use an setup with an - for instance - informix driver using a XA Datasource which doesn't fill the jdbc url and the elasticapm-agent jdbc-plugin runs in a NullPointerException).
At the same time, I want to instrument my jms message listener with the incubating ElasticAPM-agent JMS-Integration/Plugin.
Just as the documentation states and how I understand your "only one deactivated by default is 'incubating'" this is not possible, as incubating features will only be activated when I do not deactivate regular features
(which I can't as I have to deactivate JDBC in the case described above,
and - just a personal remark - 'activating something by *not* deactiving anything else' is a little bit mind-muggling)

HTH

**Comment by eyalkoren** [comment]
Fair enough- so in addition to adding general documentation on what `incubating` means, also add some info about known "risks" or expected-to-change (behaviour, data etc.).

> About the configuration:...

As [the documentation says](https://www.elastic.co/guide/en/apm/agent/java/1.x/config-core.html#config-disable-instrumentations), you can specify a list.
The default is: `disable_instrumentations == incubating`, which means only incubating instrumentations are off by default.
If you set it to: `disable_instrumentations == jdbc,redis`, then only JDBC and Redis instrumentations will be disabled, and incubating will be enabled.
There is no dependency between `incubating` and the others.

**Comment by fstendel** [comment]
Yeah,

that would be great!


@Configuration:

Oh ok, good to know that. 
We've probably been misled by "If you want to try out incubating features, set the value to an empty string." then.

Thank you :)
