### ISSUE TITLE
Instrument implementations of interfaces more efficiently

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-agent-java#932]
I have an idea to efficiently match all implementations of an interface, such as `org.asynchttpclient.AsyncHandler`. The problem is that those may be implemented as an anonymous inner class so we can’t pre-filter on the name, like `endsWith("Handler")` which means we have to check the whole inheritance hierarchy of every class in order to determine whether a class implements AsyncHandler. Instead of eagerly searching for all implementations, we could just check in `DefaultAsyncHttpClient#executeRequest(Request, AsyncHandler)` whether we have already instrumented the provided `AsyncHandler`. If we did not, we can just retransform the class and apply the corresponding instrumentation to it. We currently don’t have a facility to do that but should not be too complex to do™. 

The benefit is faster startups of the application.

**Comment by SylvainJuge** [comment]
In a previous agent I was working on, we had a kind of class index where we used to store information on all loaded classes (parent classes, interfaces, annotations, methods, ...), which was a requirement due to doing instrumentation before classes were even loaded (and of course parent/child classes are not always in the expected order).

There was of course a noticeable (but not terribly impossible to get by) impact on application startup time as the full class hierarchy was loaded from bytecode and stored in that index.

I somehow remember it was also working as a kind of cache, thus classes that weren't part of instrumented classes hierarchy got expired quickly.

In our case we instrument already loaded classes, thus regular introspection API could be used to at least discover the class structures instead of reading this from bytecode.

**Comment by felixbarny** [comment]
> In our case we instrument already loaded classes, thus regular introspection API could be used to at least discover the class structures instead of reading this from bytecode.

That's what the linked PR does. In the particular case of ensuring `AsyncHandler`s are instrumented which are provided to `org.asynchttpclient.DefaultAsyncHttpClient#execute(Request request, final AsyncHandler<T> asyncHandler)`, we know the `AsyncHandler` class and it's super classes have already been loaded. Hence, it should be safe to rely on reflection aka `AgentBuilder.DescriptionStrategy.Default.HYBRID`.
